"""birth city

Revision ID: e422d1c15ad4
Revises: 0001_initial_schema
Create Date: 2026-06-04 12:59:27.431940
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e422d1c15ad4'
down_revision: str | Sequence[str] | None = '0001_initial_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'generations',
        sa.Column(
            'birth_city',
            sa.String(length=255),
            server_default='',
            nullable=False,
        ),
    )
    op.add_column(
        'generations',
        sa.Column(
            'birth_nation',
            sa.String(length=255),
            server_default='',
            nullable=False,
        ),
    )
    op.alter_column('generations', 'birth_city', server_default=None)
    op.alter_column('generations', 'birth_nation', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'birth_nation')
    op.drop_column('generations', 'birth_city')
    # ### end Alembic commands ###
