from enum import StrEnum


class CharacterEmotion(StrEnum):
    CALM = "calm"
    CURIOSITY = "curiosity"
    PLAYFULNESS = "playfulness"
    AMUSEMENT = "amusement"
    WARMTH = "warmth"
    EMPATHY = "empathy"
    ADMIRATION = "admiration"
    HOPE = "hope"
    CONFIDENCE = "confidence"
    SURPRISE = "surprise"
    SKEPTICISM = "skepticism"
    IRRITATION = "irritation"
    FRUSTRATION = "frustration"
    ANXIETY = "anxiety"
    TENSION = "tension"
    MELANCHOLY = "melancholy"
    SADNESS = "sadness"
    BITTERNESS = "bitterness"
    INDIGNATION = "indignation"
    ANGER = "anger"
    DETERMINATION = "determination"


class HumorType(StrEnum):
    IRONY = "irony"
    SELF_IRONY = "self_irony"
    SARCASM = "sarcasm"
    HYPERBOLE = "hyperbole"
    UNDERSTATEMENT = "understatement"
    ABSURDITY = "absurdity"
    BATHOS = "bathos"
    COMIC_COMPARISON = "comic_comparison"
    REVERSAL = "reversal"
    PARODY = "parody"
    WORDPLAY = "wordplay"
    LITERALISM = "literalism"
    DEADPAN = "deadpan"
    MOCK_SERIOUSNESS = "mock_seriousness"
    COMIC_ENUMERATION = "comic_enumeration"
    PERSONIFICATION = "personification"
    FALSE_NAIVETY = "false_naivety"
    CALLBACK = "callback"
    DARK_HUMOR = "dark_humor"


class SpeechPattern(StrEnum):
    DIRECT_ADDRESS = "direct_address"
    OBSERVATION = "observation"
    RHETORICAL_QUESTION = "rhetorical_question"
    QUESTION_ANSWER = "question_answer"
    SHORT_VERDICT = "short_verdict"
    CONTRAST = "contrast"
    ANTITHESIS = "antithesis"
    GRADATION = "gradation"
    PARALLELISM = "parallelism"
    ANAPHORA = "anaphora"
    REPETITION = "repetition"
    ENUMERATION = "enumeration"
    METAPHOR = "metaphor"
    ANALOGY = "analogy"
    APHORISM = "aphorism"
    PARADOX = "paradox"
    PARENTHESIS = "parenthesis"
    ASIDE = "aside"
    DIALOGUE_IMITATION = "dialogue_imitation"
    FALSE_CONCESSION = "false_concession"
    SELF_CORRECTION = "self_correction"
    IMPERATIVE = "imperative"
    ABRUPT_SENTENCE = "abrupt_sentence"
    LONG_OBSERVATION = "long_observation"
    CALLBACK = "callback"
